feat: delta OCB binary and fixed failing tests

diff --git a/tests/prometheus_integration/goss.yaml b/tests/prometheus_integration/goss.yaml
--- a/tests/prometheus_integration/goss.yaml
+++ b/tests/prometheus_integration/goss.yaml
@@ -11,10 +11,10 @@ command:
         exit 1
       fi
       echo "Prometheus IP: $PROMETHEUS_IP"
-      # Check there is a `job` label with value `otel-collector`
+      # Check there is a `job` label with value `otelcol`
       LABELS="$(curl -s "${PROMETHEUS_IP}:9090/api/v1/label/job/values")"
       echo "Prometheus 'job' label values: $LABELS"
-      if ! echo "$LABELS" | grep -q "otel-collector"; then
-        echo "'job=otel-collector' label not found"
+      if ! echo "$LABELS" | grep -q "otelcol"; then
+        echo "'job=otelcol' label not found"
         exit 2
       fi
